server:
  port: 8083
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
hm:
  db:
    host: ${hm.db.host}
    database: ${hm.db.database}
    pw: ${hm.db.pw}
  swagger:
    title: ${hm.swagger.title}
    package: ${hm.swagger.package}
spring:
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.227.133:8858
      http-method-specify: true #是否设置请求方式作为资源名称